apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  01-init.sql: |
    CREATE TABLE IF NOT EXISTS tasks (
      id SERIAL PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      completed BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Insert sample data
    INSERT INTO tasks (title, completed) VALUES
    ('Learn Kubernetes Deployments', false),
    ('Create Services', false),
    ('Configure ConfigMaps', true),
    ('Set up StatefulSets', false),
    ('Implement Persistent Storage', false)
    ON CONFLICT DO NOTHING;
