apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres (base64 encoded)
  password: cGFzc3dvcmQxMjM=  # password123 (base64 encoded)
  database: dGFza2Ri  # taskdb (base64 encoded)
